ci:
  broken-tests-packages:
  - mpich
  - openmpi
  - py-mpi4py
  pipeline-gen:
  - build-job-remove:
      tags: [spack]
  - build-job:
      tags: [ "macos-sequoia", "apple-clang-16", "aarch64-macos" ]
  - build-job-remove:
      image:: macos-run-on-metal
