name: linux builds

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package:
          - master
          - latest-tag
    steps:
    - uses: actions/checkout@v1
    - name: Cache ccache's store
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ccache-build-${{ matrix.package }}
        restore-keys: |
          ccache-build-${{ matrix.package }}
    # - name: Cache spack's local mirror
    #   uses: actions/cache@v1
    #   with:
    #     path: ~/.mirror
    #     key: spack-mirror-${{ matrix.package }}
    #     restore-keys: |
    #       spack-mirror-${{ matrix.package }}
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install System Packages
      run: |
        sudo apt-get -yqq install git ccache openssl libssl-dev gfortran perl perl-base findutils
    - name: Clone spack
      run: |
        git clone https://github.com/spack/spack.git
    - name: Copy Configuration
      run: |
        # Set up external deps for build tests, b/c they take too long to compile
        cp .ci/*.yaml spack/etc/spack/
        ccache -M 500M && ccache -z
    - name: Run the build test
      run: |
        . spack/share/spack/setup-env.sh
        SPEC=${{ matrix.package }} ./.ci/run-build-tests.sh
        ccache -s
    - name: Dump flux logs
      if: failure()
      run: |
        . spack/share/spack/setup-env.sh
        ./.ci/dump-build-logs.sh
