name: Test Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
  
  schedule:
    - cron:  '0 4 * * *'  

jobs:
  package-builds:
    name: Test Package Builds
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # package and requiring fortran to be installed (only pmix)
        # Disabling flux-core for now, extremely borked
        package: [[flux-sched, false], [flux-pmix, true], [flux-security, false]]
        # package: [[flux-core, false], [flux-sched, false], [flux-pmix, true], [flux-security, false]]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test Build
        uses: sciworks/spack-updater/build@main
        with:
          package: ${{ matrix.package[0] }}
          fortran: "${{ matrix.package[1] == true }}"
