name: Test Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/**'
  
  schedule:
    - cron:  '0 4 * * *'  

jobs:
  package-builds:
    name: Test Package Builds
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # package and requiring fortran to be installed
        package: [[flux-core, false], [flux-sched, false], [flux-pmix, true]]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test Build
        uses: sciworks/spack-updater/build@disable-cache-clingo
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ matrix.package[0] }}
          fortran: "${{ matrix.package[1] == true }}"
