name: Test Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'

  
  schedule:
    - cron:  '0 4 * * *'  

jobs:
  package-builds:
    name: Test Package Builds
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package: [flux-core, flux-sched, flux-pmix]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Spack
        run: |
          git clone --depth 1 https://github.com/spack/spack /opt/spack
          echo "/opt/spack/bin" >> $GITHUB_PATH
          export PATH="/opt/spack/bin:$PATH"
          spack external find

      - name: Derive Microarchitecture
        run: |
          pip install archspec
          runner_cpu=$(archspec cpu)
          echo "runner_cpu=${runner_cpu}" >> $GITHUB_ENV

      - name: Clingo Cache
        uses: actions/cache@v3
        with:
          path: /opt/spack/opt/spack
          key: ${{ runner.os }}-${{ env.runner_cpu }}-clingo

      - name: Install Clingo
        run: spack install clingo

      - name: ${{ matrix.package }} Build Cache
        uses: actions/cache@v3
        with:
          path: /opt/spack/opt/spack
          key: ${{ runner.os }}-${{ env.runner_cpu }}-${{ matrix.package }}

      - name: Install pakages
        run: pip install pakages[all]

      - name: ${{ matrix.package }} Spack Build
        uses: syspack/pakages/action/install@main
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          builder: spack
          package: ${{ matrix.package }}
          repo: .
