name: Test Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
  
  schedule:
    - cron:  '0 4 * * *'  

jobs:
  package-builds:
    name: Test Package Builds
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        package: [flux-core, flux-sched, flux-pmix]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test Build
        uses: sciworks/spack-updater/build@add/tests
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ matrix.package }}
