name: Spack Upstream Updater
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 4 * * *'

jobs:
  update-spack:
    name: Pull updates from upstream spack
    runs-on: ubuntu-latest
    steps:
      - name: Update with Upstream
        uses: sciworks/spack-updater/upstream@test/vanilla-spack-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
