name: Spack Upstream Updater
on:
  pull_request: []
  workflow_dispatch:
  schedule:
    - cron:  '5 4 * * *'

jobs:
  update-spack:
    name: Pull updates from upstream spack
    runs-on: ubuntu-latest
    steps:
      - name: Update with Upstream
        uses: sciworks/spack-updater/upstream@add/tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
